# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'

target 'iOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Demo
  #pod 'Alamofire', '~> 4.8.1' # Swift 4.2
  pod 'Alamofire', '5.6.4'
  pod 'Kingfisher', '6.3.1'
  pod 'ObjectMapper', '~> 3.4.2' # Swift 4.2
  pod 'MJRefresh', '3.2.0'
  
  target 'iOSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSDemoUITests' do
    # Pods for testing
  end

end
