# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Demo
  pod 'Alamofire', '~> 4.8.1' # Swift 4.2
  pod 'AlamofireObjectMapper', '~> 5.2.0' # Swift 4.2
  pod 'ObjectMapper', '~> 3.4.2' # Swift 4.2
  
  target 'iOSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSDemoUITests' do
    # Pods for testing
  end

end
